// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members


// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0V9ZPj2lVy91smGtf3hQemK0ZNrmFj2c',
    appId: '1:51792896520:web:8f8489f385cb4ca09667bd',
    messagingSenderId: '51792896520',
    projectId: 'mobilemojlish-5f9f0',
    authDomain: 'mobilemojlish-5f9f0.firebaseapp.com',
    storageBucket: 'mobilemojlish-5f9f0.appspot.com',
    measurementId: 'G-9CBX7N0PQF', iosBundleId: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOrdu883KQOnQkIcphzdlDhVMCeT4q46o',
    appId: '1:51792896520:android:84a340f3342780d89667bd',
    messagingSenderId: '51792896520',
    projectId: 'mobilemojlish-5f9f0',
    storageBucket: 'mobilemojlish-5f9f0.appspot.com', iosBundleId: '', measurementId: '', authDomain: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd38S7OrkzRaRj3O_i39Fobx_7OSaF9fE',
    appId: '1:51792896520:ios:9d2b6f31187108499667bd',
    messagingSenderId: '51792896520',
    projectId: 'mobilemojlish-5f9f0',
    storageBucket: 'mobilemojlish-5f9f0.appspot.com',
    iosBundleId: 'com.example.mobilemojlish.mobileMojlish', measurementId: '', authDomain: '',
  );
}

class FirebaseOptions {
  const FirebaseOptions({required String apiKey, required String appId, required String messagingSenderId, required String iosBundleId, required String storageBucket, required String projectId, required String measurementId, required String authDomain});
}
